export const BUTTON_CLICKED_REQUEST = 'BUTTON_CLICKED_REQUEST';
export const BUTTON_CLICKED_SUCCESS = 'BUTTON_CLICKED_SUCCESS';
export const BUTTON_CLICKED_FAILURE = 'BUTTON_CLICKED_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';

export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';